apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: db-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app: db
        name: db
        namespace: vote
      spec:
        type: ClusterIP
        ports:
        - name: "db-service"
          port: 5432
          targetPort: 5432
        selector:
          app: db
  providerConfigRef:
    name: kubernetes-provider