apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: vote-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app: vote
        name: vote
        namespace: vote
      spec:
        type: NodePort
        ports:
        - name: "vote-service"
          port: 5000
          targetPort: 80
          nodePort: 31000
        selector:
          app: vote
  providerConfigRef:
    name: kubernetes-provider